@CampusBenchApi_HostAddress = https://localhost:63174

GET {{CampusBenchApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{CampusBenchApi_HostAddress}}/api/order
Content-Type: application/json

{
 //order
}

###
